config/routes.rb
TESST::Application.routes.draw do
  resources :homes

  root 'homes#index'

end

app/models/home.rb
class Home < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'
  #mount_uploader :avatar, AvatarUploader
  #attr_accessor :avatar, :avatar_cache, :remove_avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # Fix Can't verify CSRF token authenticity
  #skip_before_filter :verify_authenticity_token, :only => [:create]
  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
    respond_to do |format|
      format.html
      format.json {render json: @homes}
      #format.json {
      #  render :status => 200,
      #         :json => {
      #             :success => true,
      #             :message => 'OK',
      #             :data => @homes
      #         }
      #}
      #format.html {
      #  render 'homes/index'
      #}
    end
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render action: 'show', status: :created, location: @home }
      else
        format.html { render action: 'new' }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :name %>
    <%= f.text_field :name %><br />
    <%= f.label :age %>
    <%= f.text_field :age%><br />
    <br />
    <%= f.submit %>
  </div>
<% end %>
<div>
  <button id='backBoneBtn'>AAA</button>
</div>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<h1>Listing homes</h1>

<table width=100%>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Age</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%=home.id %></td>
        <td><%=home.name %></td>
        <td><%=home.age %></td>
        <td><%=link_to 'Show', home %> &nbsp; <%=link_to 'Edit', edit_home_path(home) %> &nbsp;<%=link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script type="text/template" id="search_template">
  <label>Search</label>
  <input type="text" id="search_input" />
  <input type="button" id="search_button" value="Search" />
</script>

<script type='text/template' id="add_new_template">
  <label for="name_input">Name</label>
  <input type="text" id="name_input"/>
  <label for="age_input">Age</label>
  <input type="text" id="age_input"/>
  <input type="button" id="add_new_btn" value="Add new"/>
</script>

<div id="search_container"></div>

<div id='add_new_container'></div>

<script type="text/javascript">
    SearchView = Backbone.View.extend({
        initialize: function(){
            console.log('Init Search View');
            this.render();
        },
        render: function(){
            // Compile the template using underscore
            var template = _.template( $("#search_template").html(), {} );
            // Load the compiled HTML into the Backbone "el"
            this.$el.html( template );
        }
    });

    var search_view = new SearchView({ el: $("#search_container") });
</script>

<script type="text/javascript">
    AddNewView = Backbone.View.extend({
        initialize: function(){
            console.log('Init Add New View');
            this.render();
        },
        render: function(){
            // Compile the template using underscore
            var template = _.template( $("#add_new_template").html(), {} );
            // Load the compiled HTML into the Backbone "el"
            this.$el.html( template );
        }
    });

    var add_new_view = new AddNewView({ el: $("#add_new_container") });
</script>

<%= link_to 'New Home', new_home_path %>

<!--<% content_for :javascript_includes do %>-->
    <!--<%= javascript_include_tag 'HelloBackBone.js' %>-->
<!--<% end %>-->
<%= javascript_include_tag 'HelloBackBone.js' %>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>
<%= @home.id %>
<%= @home.age %>
<%= @home.name %>
<br />


<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TESST</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <!--<%= yield :javascript_includes %>-->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>